language: java
sudo: false
install: true

jdk:
  - oraclejdk7

before_script:
  - chmod +x ./travis.sh

script:
  - ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false